#+TODO: TODO IN-PROGRESS ISSUES BETA WAITING DONE
Development notes:
* TODO:
  Mass balance
  CH4 photochem
* Open Questions:
** How to control if a species itself is active?
   Don't want to make it 'implied', meaning that, for example, a user turns off CO by not including any instances.
** How to deal with interconnectivity in mixed species environments? e.g. CH4 on but CO & CO2 off.
* TODO Error control
** repeat instances
* BETA Initialization
** Interface
   Keep everything runtime controlled. As much as possible.
*** Config
**** Read in instances
     Convert to list? As a line of entries, it is compact.
**** Read in passives
     What if name in passive list isn't an instance? Error out. %%%
     
** BETA Masks
* IN-PROGRESS Run
** BETA Surface
   Surface/external fluxes have to be handled carefully
   - fluxes 'in' can be added to a specific instance
   - fluxes 'out' have to be partitioned evenly over all instances
   MASKS!
** IN-PROGRESS Chemistry
   Chem prod goes into residual
   Chem loss depletes all instances
*** BETA CO
*** BETA CH4
*** BETA CO2
** DONE Integration
   CLOSED: [2022-12-29 Thu 22:50]
   Source terms may deplete individual instance bins
   But sink terms have to deplete the total (or all bins proportionally)

   It makes simple sense:
   
   dC/dt = P - L

   P is the linear production rate, and can be applied directly.
   L is the linear loss rate, but it has to be scaled by C_total

   L/C_total = k, so that

   dC/dt = P - kC

   ... EZPZ
   
   So what we need to do is simply set up the prod & loss terms
   then we can do whatever we want.

*** DONE Forward Euler
    CLOSED: [2022-12-29 Thu 22:51]

** What else?
* TODO Diagnostics
* TODO Finalize
* TODO Features
** coupling to other components
** using integer indexing to connect instances to other elements (e.g. fluxes, diagnostics)
   currently relies on strings. String searches are wet blankets
** BETA MASKS!
