#+TODO: TODO IN-PROGRESS ISSUES BETA WAITING DONE
Development notes:
* Open Questions:
** How to control if a species itself is active?
   Don't want to make it 'implied', meaning that, for example, a user turns off CO by not including any instances.
** How to deal with interconnectivity in mixed species environments? e.g. CH4 on but CO & CO2 off.
* TODO Error control     
* IN-PROGRESS Initialization
** Interface
   Keep everything runtime controlled. As much as possible.
*** Config
**** Read in instances
     Convert to list? As a line of entries, it is compact.
**** Read in passives
     What if name in passive list isn't an instance? Error out. %%%
     
* TODO Run
** Surface
** Chemistry
*** HOLYCRAP CO PHOTOLYSIS
    This is a mess
** Integration
   Source terms may deplete individual instance bins
   But sink terms have to deplete the total (or all bins proportionally)

   It makes simple sense:
   
   dC/dt = P - L

   P is the linear production rate, and can be applied directly.
   L is the linear loss rate, but it has to be scaled by C_total

   L/C_total = k, so that

   dC/dt = P - kC

   ... EZPZ
   
   So what we need to do is simply set up the prod & loss terms
   then we can do whatever we want.

** What else?
* TODO Finalize
* TODO Features
** coupling to other components
** using integer indexing to connect instances to other elements (e.g. fluxes, diagnostics)
   currently relies on strings. String searches are wet blankets
